### ISSUE TITLE
Cannot select file path

### ISSUE THREAD

**Issue by sheungon** [winterDroid/android-drawable-importer-intellij-plugin#97] opened 2015-10-27 15:06 UTC
![cannot_select_path](https://cloud.githubusercontent.com/assets/13306724/10761620/2e03df2e-7cfd-11e5-8ca6-c22617d4ce53.jpg)

I was trying to import image by "Batch Drawable Importer".
But I cannot expand any of the folder which trying to select image. See the image attached.
This problem was not happened in version 0.2.X

**Comment by winterDroid** [comment] 2015-10-28 10:45
Duplicate of #94

**Closed by winterDroid** 2015-10-28 10:45 UTC

**Comment by winterDroid** [comment] 2015-10-29 09:22
I just uploaded a new release to the JetBrains plugin repository. Hopefully it will be published by them soon.
