### ISSUE TITLE
Add Batch Drawable in the Newest Version(0.3.2) doesn't Work Exactly in Android Studio.

### ISSUE THREAD

**Issue by Syehunter** [winterDroid/android-drawable-importer-intellij-plugin#95] opened 2015-10-23 02:58 UTC
When press the "Add" Button, it can only show images under the root directory.
![](http://7xn4z4.com1.z0.glb.clouddn.com/drawable%20importer%20bug.jpg)

**Comment by winterDroid** [comment] 2015-10-23 04:49
This is a duplicate of #94

**Closed** 2015-10-23 04:49 UTC

**Comment by winterDroid** [comment] 2015-10-29 09:22
I just uploaded a new release to the JetBrains plugin repository. Hopefully it will be published by them soon.
