### ISSUE TITLE
Importing all files from a folder saves them to root folder

### ISSUE THREAD

**Issue by anti43** [winterDroid/android-drawable-importer-intellij-plugin#141] opened 2016-06-30 08:50 UTC
Importing one file with the batch importer works, more files are saved to c:\\<android drawablefolder names>

**Comment by hajeriwalid** [comment] 2016-07-05 21:30
Same behaviour on Android Studio 2.0

**Comment by novikk** [comment] 2016-09-05 09:16
+1

**Comment by winterDroid** [comment] 2016-10-09 14:32
I guess this is caused by an empty target root folder. Please verify that the root folder is filled. Will close this since it seems to be a duplicate of #135

**Closed by winterDroid** 2016-10-09 14:32 UTC
