### ISSUE TITLE
Add icon having black background

### ISSUE THREAD

**Issue by andhie** [winterDroid/android-drawable-importer-intellij-plugin#66] opened 2015-08-07 11:07 UTC
1) Sync to the latest Material Icons github
2) Have Android Drawable Importer plugin: 0.2.1
3) Category: content, Asset: add, Color: white

Scenario 1:
Switch the Size to 18dp, 24dp, 32dp and 48dp. Note that 18dp is the correct image, the others are have a black background 

Scenario 2:
Select any of the sizes, and proceed to add into your project. observe the actual PNG in your project, some of them will have black background. and some will not. Note: the number of spoilt PNG depends on the size that was chosen. 3 spoilt for 24dp configuration

**Comment by winterDroid** [comment] 2015-08-24 08:38
Seems to be a duplicate of #65

**Closed by winterDroid** 2015-08-24 08:38 UTC
